specVersion: 1.0.0
name: wasmswap
version: 0.0.1
runner:
  node:
    name: "@subql/node-cosmos"
    version: ">=0.1.0"
  query:
    name: "@subql/query"
    version: "*"
description: >-
  indexer for wasmswap liquidity reserves over time.
repository: https://github.com/terpnetwork/subquery-indexers
schema:
  file: ./schema.graphql

network:
  chainId: athena-3
  endpoint: https://rpc-terp.zenchainlabs.io/

dataSources:
  - kind: cosmos/Runtime
    startBlock: 1 # first block
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleSwap
          kind: cosmos/MessageHandler
          filter:
            type: "/cosmwasm.wasm.v1.MsgExecuteContract"
            contractCall: "swap"
        - handler: handlePassThroughSwap
          kind: cosmos/MessageHandler
          filter:
            type: "/cosmwasm.wasm.v1.MsgExecuteContract"
            contractCall: "pass_through_swap"
        - handler: handleSwapTo
          kind: cosmos/MessageHandler
          filter:
            type: "/cosmwasm.wasm.v1.MsgExecuteContract"
            contractCall: "swap_and_send_to"
